version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: eventos
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: spring-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/eventos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect

volumes:
  mysql_data:

#services:
#  mysql:
#    image: mysql
#    environment:
#      - 'MYSQL_DATABASE=db_example'
#      - 'MYSQL_PASSWORD=thePassword'
#      - 'MYSQL_ROOT_PASSWORD=root'
#      - 'MYSQL_USER=springuser'
#    ports:
#      - "3306:3306"
##    volumes:
##      - "./conf.d:/etc/mysql/conf.d:ro"